### ISSUE TITLE
Community of Pharmacy System - Emergency

### ISSUE THREAD

**Issue by athulmanuel** [coronasafe/telemedicine#5]
The third party software that we were using has crashed and lost the data, trying to revive it. More than 5.5 laks of accounts lost. 
this idea has been our pipeline for long hence we need to integrate it to our tele medicine system

We need to create a Community Pharmacy platform to dispense the medicines prescribed through Tele-Medicine as well as request for other requests (which are of less number). 
our Pharmacist has given a format of how he would want the page to be build up so that the billing is also taken care of. 
we will need to create a separated log in page for them. 
We have donations to provide these medicines, so the billing has to be an integral part to keep track of the payments. 

copying the link of  google doc made by our pharmacist.

https://drive.google.com/file/d/1D5mDGJUD8PSJX0JEitx-JkICkwvlgxkt/view?usp=sharing 

Kindly give suggestions and take it has high priority. Prescriptions are increasing on a daily basis.

**Comment by athulmanuel** [comment]
@bodhish any war forward on this. prescriptions are increasing day by day and the other software is not there. The whole community pharmacy system is stuck. Doctors in tele medicine has started to use the pharmacy to dispense generic medicines instead of branded medicines and we want to keep that trend running.

**Comment by bodhish** [comment]
@athulmanuel it will take us some time to get this system up and running. Can you make the Google doc public?

**Comment by bodhish** [comment]
[Pdf version of the Doc for reference](https://github.com/coronasafe/telemedicine/files/4841857/ACFrOgCO0ZbDcwDJAs4z2zBE81W58T0wSgIl-38m5p461_jdRITs84RssKX-bNsNuPUcuyiuy7iKcZkEslxnCInz-7FSopBEOVW_SGM2UFcbkf-_uYcNXIwSp0-2osyF2628Gd8Y7Kuugbli4SDj.pdf)
